### ISSUE TITLE
Permission to use website layout

### ISSUE THREAD

**Issue by TheOGUmar** [gryffyn/gryffyn.io#1]
Hey, I was wondering if I could use your website's design layout with a few major modifications on [my own website](https://umar.neocities.org/), I'll make sure to provide credits in the 'about' section of the website if that's fine with you.
Thanks!

**Comment by gryffyn** [comment]
Hey @TheOGUmar, you're welcome to use this layout. I've got a Hugo theme [in this repository](https://git.gryffyn.io/gryffyn/hugo-f5-dark), if that helps.

**Comment by TheOGUmar** [comment]
@gryffyn Its deeply appreciated, thanks
